import = ["~/.config/alacritty/themes/themes/kanagawa_dragon.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 0.95
startup_mode = "Maximized"
blur = true
padding = { x = 4, y = 4 }
option_as_alt = "Both"

[scrolling]
multiplier = 5

[font]
size = 16
normal = { family = "MesloLGM Nerd Font" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }
