import = ["~/.config/alacritty/themes/themes/ubuntu.toml"]

[window]
decorations = "None"
opacity = 0.95
startup_mode = "Maximized"
#startup_mode = "Windowed"
blur = true
padding = { x = 4, y = 4 }
option_as_alt = "Both"

[scrolling]
multiplier = 5

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font" }
#normal = { family = "Hack Nerd Font" }
#normal = { family = "FantasqueSansM Nerd Font" }
#normal = { family = "CaskaydiaCove Nerd Font" }
#normal = { family = "FiraCode Nerd Font" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }
